### ISSUE TITLE
Problems with incomplete annotation of datasets

### ISSUE THREAD

**Issue by kangben258** [matteo-dunnhofer/TREK-150-toolkit#2]
The following problem occurred when I tested my tracker
’‘’
FileNotFoundError: /TREK-150-toolkit/TREK-150/P03-P03_02-56/anchors_hoi.txt not found.
‘’‘
I check the annotation of the dataset is indeed missing this .txt file, and p03-p03_04-57 is also missing anchors_hoi.txt, maybe the annotation of other video sequences will also have this problem, I hope you can answer for me

**Comment by kangben258** [comment]
And also there is a mistake that in line19 of 'toolkit/experiments/trek150.py' you have import 'compress_file' from 'toolkit/utils/ioutils.py' , but in 'toolkit/utils/ioutils.py' there has no 'compress_file' function, I think you should change the 'compress' function to 'compress_file' function. If my thoughts are not correct I hope you can point out my mistakes

**Comment by kangben258** [comment]
> The following problem occurred when I tested my tracker ’‘’ FileNotFoundError: /TREK-150-toolkit/TREK-150/P03-P03_02-56/anchors_hoi.txt not found. ‘’‘ I check the annotation of the dataset is indeed missing this .txt file, and p03-p03_04-57 is also missing anchors_hoi.txt, maybe the annotation of other video sequences will also have this problem, I hope you can answer for me

I change the evaluate code

**Comment by kangben258** [comment]
It seems that you have not defined 'direction' in 'run_hoi' function in 'toolkit/experments/trek150.py'

**Comment by matteo-dunnhofer** [comment]
Hi @kangben258, thanks for pointing out the issues!

> The following problem occurred when I tested my tracker ’‘’ FileNotFoundError: /TREK-150-toolkit/TREK-150/P03-P03_02-56/anchors_hoi.txt not found. ‘’‘ I check the annotation of the dataset is indeed missing this .txt file, and p03-p03_04-57 is also missing anchors_hoi.txt, maybe the annotation of other video sequences will also have this problem, I hope you can answer for me

10 out of the 150 sequences do not contain interactions between the hands and the object, so there are no such annotation files in the sequence folder. I edited the code to check for the presence of the hand-object annotation files before executing the tracker.

> And also there is a mistake that in line19 of 'toolkit/experiments/trek150.py' you have import 'compress_file' from 'toolkit/utils/ioutils.py' , but in 'toolkit/utils/ioutils.py' there has no 'compress_file' function, I think you should change the 'compress' function to 'compress_file' function. If my thoughts are not correct I hope you can point out my mistakes

Thanks. I corrected the misspelling.

> It seems that you have not defined 'direction' in 'run_hoi' function in 'toolkit/experments/trek150.py'

The HOI protocol runs the tracker just in a single direction, forward in time.

**Comment by matteo-dunnhofer** [comment]
> It seems that you have not defined 'direction' in 'run_hoi' function in 'toolkit/experments/trek150.py'

The issue was fixed.
