### ISSUE TITLE
Problem during inference under HOI protocol

### ISSUE THREAD

**Issue by xljh0520** [matteo-dunnhofer/TREK-150-toolkit#3]
Hi, I got an error [here](https://github.com/matteo-dunnhofer/TREK-150-toolkit/blob/main/toolkit/experiments/trek150.py#L223) when inferencing under HOI protocol. 
```
NameError: name 'direction' is not defined
```
BTW, it seems like "dir_str" is not used.  Could you help me fix it?
Thanks in advance !

**Comment by matteo-dunnhofer** [comment]
Fixed.
