### ISSUE TITLE
Understanding the GSR Metric

### ISSUE THREAD

**Issue by bryanzhou008** [matteo-dunnhofer/TREK-150-toolkit#4]
@matteo-dunnhofer Hi there, congratulations on the great work. I am hoping to understand a little more about the GSR metric you proposed. I see that in the paper you mentioned that (for a range of thresholds combined) it measures the normalized extent of a tracking sequence before a failure, and that failure here is defined by a variable threshold on bounding box overlap. Here I'm hoping to ask is this bounding box overlap calculated between the ground truth bbox against the predicted bbox or the previous bbox against the current bbox? Thank you very much!

**Comment by matteo-dunnhofer** [comment]
Hi @bryanzhou008, the box overlap to determine the trackers' failure is computed between predicted and ground-truth bounding-boxes.
